name: Setup Fonts
description: Setup Fonts

runs:
  using: "composite"
  steps:
    - name: Download the fonts
      run: wget -nv https://github.com/be5invis/Sarasa-Gothic/releases/download/v1.0.32/SarasaGothicSC-TTF-1.0.32.7z -O sarasa.7z
      shell: bash

    - name: Unpack fonts
      run: 7z x sarasa.7z -osarasa
      shell: bash

    - name: Copy the fonts
      run: mkdir -p ~/.local/share/fonts && cp -r sarasa/* ~/.local/share/fonts/
      shell: bash

    - name: Build font information caches
      run: fc-cache -rv
      shell: bash